### ISSUE TITLE
Use path.join

### ISSUE THREAD

**Issue by craftzdog** [MrFlou/inkdrop-syncKeyMap#2]
https://github.com/MrFlou/inkdrop-syncKeyMap/blob/main/lib/sync-keymap.js#L7

Currently, the implementation does not work on Linux or macOS.
To concatenate the paths, do as following:

```js
import path from 'path'

// ...

path.join(inkdrop.keymaps.configDirPath, 'keymap.cson')
```

**Comment by MrFlou** [comment]
There we go! Thanks for the heads up and feedback!
